In [5]:
import numpy as np

In [6]:
np.__version__

'2.3.5'

In [9]:
python_list = [1,2,3,"string",6.7]

numlist = [x for x in range(10)]
print(numlist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
print(numlist*3)
print(type(numlist))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [12]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [13]:
print(arr1*3)
print(type(arr1))

[ 3  6  9 12 15]
<class 'numpy.ndarray'>


In [20]:
arr1D = np.array([1,2,3])
print(arr1D,"\n",arr1D.ndim)

[1 2 3] 
 1


In [19]:
arr2D = np.array([[1,2,3],
                  [1,2,3]])
print(arr2D,"\n",arr2D.ndim)

[[1 2 3]
 [1 2 3]] 
 2


In [17]:
arr3D = np.array([[[1,2,3],[1,2,3]],
                  [[1,2,3],[1,2,3]]])
print(arr3D,"\n",arr3D.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 
 3


In [21]:
x = np.array([])
type(x)

numpy.ndarray

In [31]:
# ndim works on object and check their dimensions

print(f"Dimension are:\t{arr1D.ndim}")
print(f"Dimension are:\t{arr2D.ndim}")
print(f"Dimension are:\t{arr3D.ndim}")

print(f"Dimension are:\t{np.shape(arr1D)}")
print(f"Dimension are:\t{np.shape(arr2D)}")
print(f"Dimension are:\t{np.shape(arr3D)}")

arr1D.dtype

Dimension are:	1
Dimension are:	2
Dimension are:	3
Dimension are:	(3,)
Dimension are:	(2, 3)
Dimension are:	(2, 2, 3)


dtype('int64')

In [29]:
size1D = arr1D.size
size1D

3

In [30]:
size1D = arr1D.size
size1D

size2D = arr2D.size
size2D

size3D = arr3D.size
size3D

12