In [5]:
import numpy as np

In [6]:
np.__version__

'2.3.5'

In [7]:
python_list = [1,2,3,"string",6.7]

numlist = [x for x in range(10)]
print(numlist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
print(numlist*3)
print(type(numlist))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [9]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [10]:
print(arr1*3)
print(type(arr1))

[ 3  6  9 12 15]
<class 'numpy.ndarray'>


In [11]:
arr1D = np.array([1,2,3])
print(arr1D,"\n",arr1D.ndim)

[1 2 3] 
 1


In [12]:
arr2D = np.array([[1,2,3],
                  [1,2,3]])
print(arr2D,"\n",arr2D.ndim)

[[1 2 3]
 [1 2 3]] 
 2


In [13]:
arr3D = np.array([[[1,2,3],[1,2,3]],
                  [[1,2,3],[1,2,3]]])
print(arr3D,"\n",arr3D.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 
 3


In [14]:
x = np.array([])
type(x)

numpy.ndarray

In [120]:
# ndim works on object and check their dimensions

print(f"Dimension are:\t{arr1D.ndim}")
print(f"Dimension are:\t{arr2D.ndim}")
print(f"Dimension are:\t{arr3D.ndim}")

print(f"Shape are:\t{np.shape(arr1D)}")
print(f"Shape are:\t{np.shape(arr2D)}")
print(f"Shape are:\t{np.shape(arr3D)}")

arr1D.dtype

Dimension are:	1
Dimension are:	2
Dimension are:	3
Shape are:	(3,)
Shape are:	(2, 3)
Shape are:	(2, 2, 3)


dtype('int64')

In [16]:
size1D = arr1D.size
size1D

3

In [17]:
size1D = arr1D.size
size1D

size2D = arr2D.size
size2D

size3D = arr3D.size
size3D

12

In [18]:
type(arr1D)

numpy.ndarray

In [19]:
arr1D.dtype

dtype('int64')

In [20]:
arr1D.size

3

In [21]:
arr1D.shape

(3,)

In [22]:
print(arr1D)

[1 2 3]


In [23]:
arr1D * 10

array([10, 20, 30])

In [24]:
arr1D + arr1D

array([2, 4, 6])

a = 7
b = 2
print('Sum: ', a + b) # Addition
print('Subtraction: ', a - b) # Subtraction
print('Multiplication: ', a * b) # Multiplication
print('Division: ', a / b) # Division
print('Floor Division: ', a // b) # Floor Division
print('Modulo: ', a % b) # Modulo
print('Power: ', a ** b) # Power

In [25]:
arr1 = np.array([1,2,3])
print(arr1)

arr2 = np.array([10,20,30])
print(arr2)

print("Result: ", arr1 - arr2)

[1 2 3]
[10 20 30]
Result:  [ -9 -18 -27]


In [26]:
arr1 = np.array([1,2,3])
print(arr1)

arr2 = np.array([10,20,30])
print(arr2)

print("Result: ", arr1 * arr2)

[1 2 3]
[10 20 30]
Result:  [10 40 90]


In [27]:
arr1 = np.array([1,2,3])
print(arr1)

arr2 = np.array([10,20,30])
print(arr2)

print("Result: ", arr1 ** arr2)

[1 2 3]
[10 20 30]
Result:  [              1         1048576 205891132094649]


In [ ]:
prices = np.array([4000000,3500000,2500000])
print(f"The prices are: \t {prices/1000000}million") #scale data

The prices are: 	 [4.  3.5 2.5]million


In [ ]:
#slicing
#reshaping

In [131]:
range_of_number = np.arange(10)
range_of_number

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
range_of_number = np.arange(1,11)
print(range_of_number)

[ 1  2  3  4  5  6  7  8  9 10]


In [133]:
range_of_number = np.arange(1,11)
print(range_of_number)

range_of_number.reshape(5,2)

[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [134]:
range_of_number = np.arange(1,11)
print(range_of_number)

range_example=np.arange(1,11).reshape(5,2)
range_example

[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [34]:
#only list comprehension we use

nums= [x for x in range (0,101,2)]
print(nums)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [37]:
nums1 = nums[0:25:3]
nums1

[0, 6, 12, 18, 24, 30, 36, 42, 48]

In [43]:
# create from list to array

nums1 = nums[100:0:-1]
arraynums = np.array(nums)
print(arraynums)

print(arraynums[100:25:-1])


[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52]


In [44]:
print(arraynums[:2])

[0 2]


In [46]:
line = np.linspace(0,1,10) # values are evenly spaced and stored in array
line

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [51]:
line = np.linspace(0,1,11)
line

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [53]:
np.zeros((3,3))
np.ones((4,3))

# takes in tuples of shape and return arrays

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
randomArray = np.random.rand(3,4)
randomArray

array([[0.42175804, 0.39390821, 0.23222257, 0.4416646 ],
       [0.37302139, 0.58360604, 0.10003138, 0.74135188],
       [0.08319793, 0.12622394, 0.32289153, 0.64292729]])

In [75]:
# random class in numpy
# numbers

randomArray = np.random.rand(3,4)
randomArray

randomArray = np.random.randint(0,100,(3,3)) # start, stop, (shape)
randomArray

array([[48, 11,  7],
       [90, 29, 47],
       [50, 46, 94]], dtype=int32)

In [86]:
np.random.seed(40)


randomArray = np.random.randint(0,100,(3,4))
randomArray

array([[70, 91,  7, 37],
       [56, 50, 65, 12],
       [71, 19, 31, 74]], dtype=int32)

In [88]:
# change and reshape
# transform, linear algebra

flatarray = randomArray.flatten()
flatarray

rehapedarray = flatarray.reshape(6,2)
rehapedarray



array([[70, 91],
       [ 7, 37],
       [56, 50],
       [65, 12],
       [71, 19],
       [31, 74]], dtype=int32)

In [89]:
#transform

rehapedarray.T

array([[70,  7, 56, 65, 71, 31],
       [91, 37, 50, 12, 19, 74]], dtype=int32)

In [91]:
#aggregation
data = np.array([85,94,22,68,94,54,98]) #marks

#sum
#mean
#min max

print(data.sum())

515


In [ ]:
# exercise
# create a list of 1 to 10
# use list comprehension
# give me the addition of numbers from 1 to 10

nums= [x for x in range (1,11)]

total = sum(nums)

print("List:", nums)
print("Sum:", total)


List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Sum: 55


In [118]:
# jawapan sebenar

arrayy = np.array([num for num in range(1,11)])
sum_of_array = arrayy.sum()
print(sum_of_array)




55


In [119]:
arrayy.max()

np.int64(10)

In [124]:
a_2d_matrix = np.ones((3,5))
print(a_2d_matrix)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# axis=0 → jumlahkan setiap kolum (menegak).
# axis=1 → jumlahkan setiap baris (mendatar).
# column wise sum
a_2d_matrix.sum(axis=0)



array([3., 3., 3., 3., 3.])

In [130]:
a_2d_matrix.sum(axis=1)

array([5., 5., 5.])

splitting numpy array

In [140]:
dataset = np.arange(1,101).reshape(50,2)
print(dataset)

train_dataset = dataset[:25]
test_dataset = dataset[25:]
print(test_dataset)

[[  1   2]
 [  3   4]
 [  5   6]
 [  7   8]
 [  9  10]
 [ 11  12]
 [ 13  14]
 [ 15  16]
 [ 17  18]
 [ 19  20]
 [ 21  22]
 [ 23  24]
 [ 25  26]
 [ 27  28]
 [ 29  30]
 [ 31  32]
 [ 33  34]
 [ 35  36]
 [ 37  38]
 [ 39  40]
 [ 41  42]
 [ 43  44]
 [ 45  46]
 [ 47  48]
 [ 49  50]
 [ 51  52]
 [ 53  54]
 [ 55  56]
 [ 57  58]
 [ 59  60]
 [ 61  62]
 [ 63  64]
 [ 65  66]
 [ 67  68]
 [ 69  70]
 [ 71  72]
 [ 73  74]
 [ 75  76]
 [ 77  78]
 [ 79  80]
 [ 81  82]
 [ 83  84]
 [ 85  86]
 [ 87  88]
 [ 89  90]
 [ 91  92]
 [ 93  94]
 [ 95  96]
 [ 97  98]
 [ 99 100]]
[[ 51  52]
 [ 53  54]
 [ 55  56]
 [ 57  58]
 [ 59  60]
 [ 61  62]
 [ 63  64]
 [ 65  66]
 [ 67  68]
 [ 69  70]
 [ 71  72]
 [ 73  74]
 [ 75  76]
 [ 77  78]
 [ 79  80]
 [ 81  82]
 [ 83  84]
 [ 85  86]
 [ 87  88]
 [ 89  90]
 [ 91  92]
 [ 93  94]
 [ 95  96]
 [ 97  98]
 [ 99 100]]
